# Generated by Django 5.1 on 2024-09-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRolCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.categoria')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Rol Categoria',
                'verbose_name_plural': 'Usuarios Roles Categorías',
                'unique_together': {('usuario', 'rol', 'categoria')},
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
