# Generated by Django 5.1 on 2024-10-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('alcance', 'Alcance'), ('mas likeado', 'Mas likeado'), ('mas leido', 'Mas leido'), ('publicado por tiempo', 'Publicado por tiempo'), ('redactado por tiempo', 'Redactado por tiempo'), ('tiempo de revision', 'Tiempo de revision'), ('articulos inactivados por tiempo', 'Articulos inactivados por tiempo')], max_length=100)),
            ],
        ),
    ]
