# Generated by Django 5.1 on 2024-10-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='descripcion',
            new_name='html_content',
        ),
    ]
