# Generated by Django 5.1 on 2024-10-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_rename_descripcion_reporte_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='estado',
            new_name='tipo',
        ),
    ]
