# Generated by Django 5.1 on 2024-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0002_publicacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='texto_corto',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='texto_largo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
