# Generated by Django 5.1 on 2024-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0003_publicacion_cita_alter_publicacion_imagen1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='texto_corto',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicacion',
        ),
    ]
