# Generated by Django 5.1 on 2024-09-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0004_alter_publicacion_texto_corto_and_more'),
        ('login', '0002_usuariorolcategoria_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.categoria'),
            preserve_default=False,
        ),
    ]
