# Generated by Django 5.1 on 2024-09-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0005_publicacion_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='texto_corto',
            new_name='contenido_html',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='texto_largo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('rechazado', 'Rechazado'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
    ]
