# Generated by Django 5.1 on 2024-09-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
