# Generated by Django 5.1 on 2024-09-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0009_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='me_gustas',
            field=models.IntegerField(default=0),
        ),
    ]
