# Generated by Django 5.1 on 2024-10-28 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0012_alter_publicacion_fecha_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('modificado', 'Modificado'), ('cambio_estado', 'Cambio de Estado'), ('eliminado', 'Eliminado')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=10, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='crearpublicaciones.publicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_publicacion',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
