# Generated by Django 5.1 on 2024-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0013_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('modificado', 'Modificado'), ('cambio_estado', 'Cambio de Estado'), ('eliminado', 'Eliminado'), ('inactivado', 'Inactivado')], max_length=20),
        ),
    ]
