# Generated by Django 5.1 on 2024-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearpublicaciones', '0014_alter_historial_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('modificado_titulo_cuerpo', 'Titulo y Cuerpo Modificado'), ('modificado_titulo', 'Titulo Modificado'), ('modificado_cuerpo', 'Cuerpo Modificado'), ('cambio_estado', 'Cambio de Estado'), ('eliminado', 'Eliminado'), ('inactivado', 'Inactivado')], max_length=24),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('rechazado', 'Rechazado'), ('publicado', 'Publicado'), ('inactivo', 'Inactivo')], default='borrador', max_length=10),
        ),
    ]
